WelcomePopUp Component: Walking skelleton complete.
FPJN-IIC3143-1/fpjn-iic3143-1.github.io pull request #30
Opened 2024-11-09 19:11 UTC by PipeOlivares

2024-11-10 16:44 UTC, Dafnemami reviewed
Se ve robusto el componente y sus archivos asociados. Veo que quedan pendientes los siguientes items a resolver:

- Validación de datos ingresados. 
- Indicar formato de fecha de expiración a ingresar (quizá que input sea de type=date o similar)
- Integrar componente al flujo del usuario nuevo, esto es, que le aparezca como pop-up al loggearse por primera vez.
- Fuente de título "Bienvenido/a MealsBuddy"
- No permitir que el usuario cierre el pop-up hasta que lo haya enviado (caso en el que componente debe cerrarse solo)
- Sobre los inputs agregar estilo de focus y hover.

2024-11-10 16:50 UTC, Dafnemami requested changes
Se ve robusto el componente y sus archivos asociados. Dejé comentarios en el código, pero también te dejo de forma general lo que falta por resolver:
1. Validación de datos ingresados.
2. Indicar formato de fecha de expiración a ingresar (quizá que input sea de type=date o similar)
3. Integrar componente al flujo del usuario nuevo, esto es, que le aparezca como pop-up al loggearse por primera vez.
4. Fuente de título "Bienvenido/a MealsBuddy"
5. No permitir que el usuario cierre el pop-up hasta que lo haya enviado (caso en el que componente debe cerrarse solo)
6. Sobre los inputs agregar estilo de focus y hover.

2024-11-10 16:50 UTC, Dafnemami commented on app/components/creditCardInput.jsx
> +          />
Este input debería indica al usuario con un placehodler el formato de la fecha a ingresar

2024-11-10 16:50 UTC, Dafnemami commented on app/components/creditCardInput.jsx
> +
Este handler genérico no valida los datos. quizá probar con handlers más específicos para validar acorde al contexto cada entrada según input

2024-11-10 16:50 UTC, Dafnemami commented on app/components/welcomePopUp.jsx
> +              <div className="text-xl text-gray-100 font-bold font-serif">Bienvenido/a MealsBuddy!</div>
quitar "font-serif" *es otra fuente). la fuente general fue definida en tailwind.css, no se debe volver a sobreescribir

2024-11-10 16:50 UTC, Dafnemami commented on app/components/welcomePopUp.jsx
> +              <div className="text-gray-300 text-xl text-gray-150 ">Para comenzar, por favor completa tus datos:</div>
dejar estos dos con el mismo tamaño de fuente.

2024-11-11 01:41 UTC, PipeOlivares commented on app/components/creditCardInput.jsx
> +          />
Placeholder queda implementado, junto a las validaciones.

2024-11-11 01:42 UTC, PipeOlivares commented on app/components/creditCardInput.jsx
> +
Nuevo handler que implementa validaciones, queda implementado.

2024-11-11 01:42 UTC, PipeOlivares commented on app/components/welcomePopUp.jsx
> +              <div className="text-xl text-gray-100 font-bold font-serif">Bienvenido/a MealsBuddy!</div>
Toda la razón, font-serif queda eliminado para mantener estándar de fuentes a lo largo de la plataforma.

2024-11-11 01:42 UTC, PipeOlivares commented on app/components/welcomePopUp.jsx
> +              <div className="text-gray-300 text-xl text-gray-150 ">Para comenzar, por favor completa tus datos:</div>
Quedaron con mismo tamaño de fuente y se formatearon mejor.

2024-11-11 01:47 UTC, Dafnemami approved these changes
Está perfecto. Cambios bien implementados. Se aprueba la PR.

2024-11-11 01:47 UTC, merged