view r.list done + recipeCard overflow proof
FPJN-IIC3143-1/fpjn-iic3143-1.github.io pull request #44
Opened 2024-11-25 02:58 UTC by Dafnemami

view recipes list is created. Also, recipe card was modified in two ways. first, a title+subtitle was added. second, it was modified to be overflow (of text) proof.

2024-11-25 12:31 UTC, PipeOlivares commented on app/components/recipeCard.jsx
Apruebo los cambios a recipeCard

2024-11-25 12:32 UTC, PipeOlivares commented on app/components/recipePopUp.jsx
Estos cambios generarán conflicto con mi rama de recipePopUp pero se resolverán desde mi rama! 
Aceptados

2024-11-25 12:36 UTC, PipeOlivares requested changes
Queda solo un cambio requested en recipe-list.jsx.

2024-11-25 12:36 UTC, PipeOlivares commented on app/routes/recipes-list.jsx
> +          <RecipeCard N={1} leftRowInfo={["600g", "600g", "600g", "600g"]} rightRowInfo={["Pollo", "Yogurt Natural", "Albahaca", "Queso parmesano president"]} />
Existen 3 Placeholders, ideal que sean diferentes para probar diferentes casos, por ejemplo que alguno de ellos tenga más ingredientes y ver si el componente hace overflow correctamente.

2024-11-28 16:23 UTC, Dafnemami commented on app/components/recipePopUp.jsx
perfecto!

2024-11-28 16:23 UTC, Dafnemami commented on app/components/recipeCard.jsx
súper!

2024-11-28 16:24 UTC, Dafnemami commented on app/routes/recipes-list.jsx
> +          <RecipeCard N={1} leftRowInfo={["600g", "600g", "600g", "600g"]} rightRowInfo={["Pollo", "Yogurt Natural", "Albahaca", "Queso parmesano president"]} />
buen punto. overflow horizontal si quedó manejado. probaré con el vertical

2024-11-28 16:36 UTC, Dafnemami commented on app/routes/recipes-list.jsx
> +          <RecipeCard N={1} leftRowInfo={["600g", "600g", "600g", "600g"]} rightRowInfo={["Pollo", "Yogurt Natural", "Albahaca", "Queso parmesano president"]} />
Ahora lo dejé corregido. También, se me había pasado dejar el título de la receta como un argument del RecipeCard. Esto último también quedó corregido.

2024-11-28 16:49 UTC, PipeOlivares approved these changes
Quedan claro los cambios implementados. Los revisé y los apruebo.

2024-11-28 16:51 UTC, merged